### ISSUE TITLE
error: use of undeclared identifier 'NSString'; did you mean 'cString'?

### ISSUE THREAD

**Issue by whoamigo** [r-lyeh/v1#37]
Hi @r-lyeh,

I can't get past this point while compiling with `sh MAKE.bat`:

```shell
editor
demo_audio
In file included from editor.c:67:
In file included from ./fwk.c:93:
3rd_glfw3.h:33606:5: error: use of undeclared identifier 'NSString'; did you mean 'cString'?
    NSString* appName = nil;
    ^~~~~~~~
    cString
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Frameworks/OpenScripting.framework/Headers/ASRegistry.h:212:3: note: 'cString' declared here
  cString                       = cStringClass /* old name for cStringClass - can't be used in .r files*/
  ^
In file included from editor.c:67:
In file included from ./fwk.c:93:
3rd_glfw3.h:33606:15: error: use of undeclared identifier 'appName'
    NSString* appName = nil;
```

This should not happen since `-framework cocoa` normally also includes Foundation. I also tried adding `-framework foundation` to no avail.

P.S. - I'm looking forward to trying the new editor 👍

**Comment by r-lyeh** [comment]
hey @whoamigo, let me check. havent compiled on osx actually since weeks ago

**Comment by r-lyeh** [comment]
well, i guess the editor had to be compiled as objective-c (i missed to add the `-ObjC` flag). let me know if that works for you now

**Comment by whoamigo** [comment]
It works! The new editor is super cool!!! 💯 🥇

**Comment by r-lyeh** [comment]
thanks! still a wip editor. i dont think it will be ready for "production" till late summer!

**Comment by whoamigo** [comment]
It  also really drop its fps when in the background. Cool!!!

**Comment by r-lyeh** [comment]
it also has some fancy window animations and resizes. especially if windows (which can be enabled from top-left icon) are sharing border edges
